# Generated by Django 6.0.3 on 2026-06-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_projects',
            field=models.IntegerField(default=25, help_text='Most projects this user may own at once. New creations are rejected at the cap. 0 blocks project creation entirely.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_upload_mb',
            field=models.IntegerField(default=250, help_text='Per-user ZIP upload cap in MB. The global SAST_MAX_UPLOAD_SIZE_MB still applies on top of this. 0 blocks the upload source type entirely.'),
        ),
    ]
