"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'scans',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'sast_db'),
        'USER': os.getenv('DATABASE_USER', 'postgres'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'postgres'),
        'HOST': os.getenv('DATABASE_HOST', 'localhost'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Display timezone. Storage stays UTC (USE_TZ=True); this only affects
# what templates render. Override in .env, e.g. TIME_ZONE=Europe/Paris.
TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Uploaded source archives land here.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Sprint 2 source-ingest limits, all env-overridable.
# The compressed cap is enforced at upload time by Django; the
# extracted cap is enforced inside PathResolver._resolve_upload before
# extraction (zip-bomb defense).
SAST_MAX_UPLOAD_SIZE_MB = int(os.getenv("SAST_MAX_UPLOAD_SIZE_MB", "250"))
SAST_MAX_EXTRACTED_SIZE_MB = int(os.getenv("SAST_MAX_EXTRACTED_SIZE_MB", "750"))
DATA_UPLOAD_MAX_MEMORY_SIZE = SAST_MAX_UPLOAD_SIZE_MB * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = SAST_MAX_UPLOAD_SIZE_MB * 1024 * 1024

# Git-clone timeout in seconds for the `git` source type.
SAST_GIT_CLONE_TIMEOUT = int(os.getenv("SAST_GIT_CLONE_TIMEOUT", "60"))

# Auth
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/projects/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# SonarQube profile defaults — read from env so they can be set per
# deployment without code changes. A per-project override moves into
# the Project model in Sprint 3.
SONAR_HOST = os.getenv("SONAR_HOST", "http://localhost:9000")
SONAR_TOKEN = os.getenv("SONAR_TOKEN")
SONAR_PROJECT_KEY = os.getenv("SONAR_PROJECT_KEY")

# Semgrep CLI path. None = auto-discover via PATH (shutil.which).
SEMGREP_PATH = os.getenv("SEMGREP_PATH")

# sonar-scanner CLI path (the uploader, not the SonarQube server). None
# = auto-discover via PATH.
SONAR_SCANNER_PATH = os.getenv("SONAR_SCANNER_PATH")

# How long the SonarAdapter polls SonarQube's task queue waiting for a
# scan upload to finish processing on the server side. 2s interval +
# 5min total cap covers any realistic project size.
SAST_SONAR_POLL_INTERVAL = float(os.getenv("SAST_SONAR_POLL_INTERVAL", "2"))
SAST_SONAR_POLL_TIMEOUT = float(os.getenv("SAST_SONAR_POLL_TIMEOUT", "300"))

# Which Sonar issue types to import. Modern SonarQube's /api/issues/search
# accepts only CODE_SMELL, BUG, VULNERABILITY (security hotspots moved
# to a separate /api/hotspots/search endpoint). Default to VULNERABILITY
# to match this platform's OWASP-Top-10 framing. Set
# SAST_SONAR_ISSUE_TYPES="" in .env to import everything.
SAST_SONAR_ISSUE_TYPES = os.getenv(
    "SAST_SONAR_ISSUE_TYPES", "VULNERABILITY"
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "format": (
                '{"level": "%(levelname)s", '
                '"timestamp": "%(asctime)s", '
                '"module": "%(module)s", '
                '"message": "%(message)s"}'
            )
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "scans": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
