# Generated by Django 6.0.3 on 2026-03-23 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('repo_path', models.CharField(max_length=500)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scans.project')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=50)),
                ('rule_id', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('message', models.TextField()),
                ('cwe_id', models.CharField(blank=True, max_length=50)),
                ('owasp_category', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='scans_proje_created_d2bcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['project', 'started_at'], name='scans_scan_project_9e605a_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['severity'], name='scans_findi_severit_8cda33_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['owasp_category'], name='scans_findi_owasp_c_e60f7c_idx'),
        ),
    ]
