# Generated by Django 6.0.3 on 2026-05-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scan_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cwe_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='finding',
            name='owasp_category',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
