# Generated by Django 6.0.3 on 2026-05-05 04:07

import scans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_alter_finding_cwe_id_alter_finding_owasp_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='source_archive',
            field=models.FileField(blank=True, null=True, upload_to=scans.models._archive_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local path'), ('upload', 'Uploaded archive'), ('git', 'Git repository')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
