# Generated by Django 6.0.3 on 2026-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_normalize_source_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sonar_project_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
