# Generated by Django 6.0.3 on 2026-05-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_backfill_sonar_project_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonarSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('host', models.URLField(blank=True, help_text='SonarQube server URL, e.g. http://localhost:9000. Leave blank to use SONAR_HOST from .env.')),
                ('token', models.CharField(blank=True, help_text='Admin token from SonarQube (My Account → Security). Leave blank to use SONAR_TOKEN from .env.', max_length=200)),
                ('issue_types', models.CharField(blank=True, help_text='Comma-separated. Default: "VULNERABILITY". Use "VULNERABILITY,BUG,CODE_SMELL" to import everything. Leave blank to use SAST_SONAR_ISSUE_TYPES from .env.', max_length=200)),
            ],
            options={
                'verbose_name': 'Sonar settings',
                'verbose_name_plural': 'Sonar settings',
            },
        ),
    ]
