# Generated by Django 6.0.3 on 2026-06-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_sonarsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('hide_local_source', models.BooleanField(default=False, help_text='Production safety: refuse the local-path source type for new projects (existing local projects keep working).')),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.AddField(
            model_name='sonarsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sonarsettings',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
