# Generated by Django 6.0.3 on 2026-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_hide_local_source_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
