# Generated by Django 6.0.3 on 2026-06-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_finding_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonarsettings',
            name='include_hotspots',
            field=models.BooleanField(default=True, help_text="Show SonarQube Security Hotspots in scan results. Off drops them from the findings view and the type menu (they're still scanned, just not surfaced)."),
        ),
    ]
